### ISSUE TITLE
Eval request result.csv

### ISSUE THREAD

**Issue by dvhphuc** [simplify23/CDistNet#12]
Hello,
I don't know what is result.csv and how to to get it?
Thank you

**Comment by simplify23** [comment]
Our model has result.csv for saving result data. I don't think it's necessary to create. Maybe another error happens.
https://github.com/simplify23/CDistNet/blob/7803adf91125bd3cd608bef20395d51779cb4c7a/eval.py#L222
https://github.com/simplify23/CDistNet/blob/7803adf91125bd3cd608bef20395d51779cb4c7a/eval.py#L197

**Comment by dvhphuc** [comment]
Thank you
