### ISSUE TITLE
Can it work with phone number ?

### ISSUE THREAD

**Issue by KaiserImmortal** [simplify23/CDistNet#13]
I trained the model with billboards but when I inference it, it doesn't work well with sequences of numbers or phone numbers. Can you help me? Thanks very much.

**Comment by simplify23** [comment]
i think you can refer to this #10. Set phone numbers as your dict.

**Comment by KaiserImmortal** [comment]
> i think you can refer to this #10. Set phone numbers as your dict.
@simplify23  Sorry, you seem to be misunderstanding my question. In my dict.txt there are numeric characters from 0 to 9. I would like to ask you if your model can work with phone number sequence strings?. When I inference, it only recognizes the first numbers of the sequence, the second part is generated or incorrect. Although it still detects enough numeric characters, it fails to recognize the last numbers in the number sequence. Thanks

**Comment by KaiserImmortal** [comment]
Example: 
GT: 0123526810
Pre: 0123456789

**Comment by simplify23** [comment]
Our model can fully recognize numbers, even with the previous dictionary. You can fine-tune the pre-trained model for debugging to determine where the error occurred.

**Comment by KaiserImmortal** [comment]
> Our model can fully recognize numbers, even with the previous dictionary. You can fine-tune the pre-trained model for debugging to determine where the error occurred.

 With 250 characters both numbers and letters, which part of the model should I fine tune. Can you suggest?

**Comment by simplify23** [comment]
> Example: GT: 0123526810 Pre: 0123456789

I guess you need more training datasets.  If you just need numbers, you can predict step by step with pre-train model like `<s> -> <s>, 0 -> .... -> <s> 0,,1,2,3,4,5,5,6,7,8,9,<end>.` I hope it can help you.

**Comment by KaiserImmortal** [comment]
> > Example: GT: 0123526810 Pre: 0123456789
> 
> I guess you need more training datasets. If you just need numbers, you can predict step by step with pre-train model like `<s> -> <s>, 0 -> .... -> <s> 0,,1,2,3,4,5,5,6,7,8,9,<end>.` I hope it can help you.

Thank you very much, i just inference with pretrained model and it work well with phone numbers. I will make more dataset and retrain

**Comment by nab1010** [comment]
> > > Example: GT: 0123526810 Pre: 0123456789
> > 
> > 
> > I guess you need more training datasets. If you just need numbers, you can predict step by step with pre-train model like `<s> -> <s>, 0 -> .... -> <s> 0,,1,2,3,4,5,5,6,7,8,9,<end>.` I hope it can help you.
> 
> Thank you very much, i just inference with pretrained model and it work well with phone numbers. I will make more dataset and retrain
