### ISSUE TITLE
accuracy is lower than other models

### ISSUE THREAD

**Issue by bharatsubedi** [simplify23/CDistNet#4]
I tried to train your model but I got accuracy is lower than other transformer models. could you please let me know how can I got higher accuracy ?

**Comment by simplify23** [comment]
what methods do you mean other transformer models?   If you need some help, please provide the following things: your CDistNet_config, the accuracy of CDistNet in six benchmarks, the accuracy of other methods in six benchmarks. Please strictly follow our configuration for training

**Comment by bharatsubedi** [comment]
Thank you I will check config and train again.
