### ISSUE TITLE
Inference Time

### ISSUE THREAD

**Issue by bharatsubedi** [simplify23/CDistNet#5]
I tried your network and got a good result but I faced the problem of inference speed. could you please let me know I can increase the speed of recognition?

**Comment by simplify23** [comment]
Compared with the parallel attention mechanism, our method has no advantage in inference speed, but it is not far behind the traditional encoder-decoder method. If speed of reasoning is required, try decoding 2-3 characters at one timestep, or distil a CTC student network. We plan to design a rapid inference version of CDistNet V2 later.

**Comment by bharatsubedi** [comment]
changed the network structure and got faster inferencing time now.
 Thank you very much.

**Comment by WongVi** [comment]
> Compared with the parallel attention mechanism, our method has no advantage in inference speed, but it is not far behind the traditional encoder-decoder method. If speed of reasoning is required, try decoding 2-3 characters at one timestep, or distil a CTC student network. We plan to design a rapid inference version of CDistNet V2 later.

waiting rapid  version
