### ISSUE TITLE
Is it possible to inference on images 

### ISSUE THREAD

**Issue by saichandra1199** [simplify23/CDistNet#9]
Here i came to know that we are taking predictions on lmdb dataset. So is there any chance to get results out of images ?

**Comment by simplify23** [comment]
I don't quite understand you mean. Do you mean to evaluate with other lmdb datasets ?

**Comment by saichandra1199** [comment]
@simplify23 It means like is there any inference script so that we can direct test the model on images rather than lmdb files

**Comment by simplify23** [comment]
@saichandra1199  our code support for testing by txt labels. You can set `cfg.test.is_test_gt` in Config file for test, some code need to be change.

**Comment by saichandra1199** [comment]
@simplify23 so you are saying that we need ground truth txt file for every image which needs to be tested. Is that right ?
Can't we get direct predictions over set of images given using a model which is trained
So what you're saying that cfg.test.is_test_gt = True and i've to give image_dir path consisting of images and a txt file which consists of image name and ground truth text seperated by space

**Comment by simplify23** [comment]
If you can't get real txt labels, you can also try this method. The prediction result will save as `submit.txt`,you just need empty txt or note other code.
You can read the eval.py line 180  for change.
```       
gt_file = os.path.join(cfg.test.model_dir, 'gt.txt')
pred_file = os.path.join(cfg.test.model_dir, 'submit.txt')
name_file = os.path.join(cfg.test.model_dir, 'name.txt')
write_to_file(gt_file, gt_list)
write_to_file(pred_file, pred_list)
write_to_file(name_file, name_list)
```
